#!/bin/sh

if mountpoint -q /target; then
	echo "Installing ZED to /target"
	cp /zed /target
else
	echo "/target is not a mountpoint."
	echo "You should re-run this container with -v /usr/local/bin:/target"
fi
