#!/bin/sh

zeddir() {
  local container=$1
  local zeddir=$2
  : ${container:? required}
  : ${zeddir:? required}

  docker inspect zed-server &> /dev/null && echo zed-server is already running 1>&2 || docker run -d --name zed-server -p 7337:7337 --entrypoint=/bin/sh zed -c "/zedrem --server"
  local zedip=$(docker inspect -f "{{.NetworkSettings.IPAddress}}" zed-server)

  docker run --rm --entrypoint=sh zed -c 'cat /zedrem' \
    | docker-enter $container sh -c 'cat>/zedrem'
  docker-enter $container sh -c 'chmod +x /zedrem'

  docker-enter $container sh -c "/zedrem -u ws://${zedip}:7337 ${zeddir}"
}

zeddir "$@"
